# Generated by Django 3.1.3 on 2020-11-21 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 3, 37, 7, 862549)),
        ),
    ]
